# Generated by Django 4.1.5 on 2023-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpsons_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpsons',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
