# Generated by Django 4.1.5 on 2023-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpsons_app', '0002_simpsons_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpsons',
            name='id',
        ),
        migrations.AddField(
            model_name='simpsons',
            name='simpson_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
